com.tark.query.builder.autoconfigure.TarkQBuilderSqlAutoConfiguration=
com.tark.query.builder.autoconfigure.TarkQBuilderSqlAutoConfiguration.ConditionalOnClass=org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
